#!/bin/bash

echo Setting up database $TEST_DATABASE_NAME
dropdb $TEST_DATABASE_NAME
createdb $TEST_DATABASE_NAME
echo Running migrations
for d in migrations/*/ ; do
  echo "$d"
  psql $TEST_DATABASE_NAME < "$d"up.sql
done
NODE_ENV=test npm run start
